wandb_version: 1

epochs:
  value: 10000
hidden_size:
  value: 16
learning_rate:
  value: 0.004595290065329516
num_layers:
  value: 4
optimizer:
  value: AdamW
weight_decay:
  value: 0.004243551413027796
