wandb_version: 1

epochs:
  value: 10000
hidden_size:
  value: 16
learning_rate:
  value: 0.0024456664241947436
num_layers:
  value: 4
optimizer:
  value: AdamW
weight_decay:
  value: 1.4307963331657946e-12
