wandb_version: 1

epochs:
  value: 10000
hidden_size:
  value: 16
learning_rate:
  value: 0.00023821311900009835
num_layers:
  value: 4
optimizer:
  value: AdamW
weight_decay:
  value: 9.72830762359407e-08
