wandb_version: 1

epochs:
  value: 10000
hidden_size:
  value: 16
learning_rate:
  value: 0.0016407256989791983
num_layers:
  value: 4
optimizer:
  value: AdamW
weight_decay:
  value: 7.271953532963932e-05
