wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.7
    cli_version: 0.18.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1733350893
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.12.7
      5: 0.18.7
      8:
      - 3
      - 5
      13: windows-amd64
hidden_layers:
  desc: null
  value: 4
hidden_size:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.01
weight_decay:
  desc: null
  value: 1.0e-05
