_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.7
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
epochs:
    value: 10000
hidden_size:
    value: 16
learning_rate:
    value: 0.0005459090708957397
num_layers:
    value: 4
weight_decay:
    value: 9.041732566614342e-09
