_wandb:
    value:
        cli_version: 0.18.7
        code_path: code/scripts/lotka-volterra-upinn.py
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
Archtechture:
    value: FNN
Epochs:
    value: 10
Optimizer:
    value: AdamW
Problem:
    value: Lotka-Volterra
learning_rate:
    value: 0.001
