_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 2
                - 13
                - 23
                - 24
                - 55
            "4": 3.12.7
            "5": 0.18.7
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
epochs:
    value: 10000
hidden_size:
    value: 16
learning_rate:
    value: 0.00340083483612245
num_layers:
    value: 4
weight_decay:
    value: 8.135471810993832e-09
